### ISSUE TITLE
Table of content markup support

### ISSUE THREAD

**Issue by prosoitos** [niklasfasching/go-org#23]
Hi!

I am using org-mode in Hugo and I am unable to select the number of header levels in the TOC.

In my config.toml, I have:

```toml
[markup]
  [markup.tableOfContents]
    endLevel = 1
    ordered = false
    startLevel = 1
```

And, if I write my content in markdown, I do have one level of header in my TOC (as expected). But if I use org-mode, I have 3 levels.

Since org-mode does not seem to take the config.toml into effect for the TOC, I tried to play with classic org-mode options (which is probably very naive) by adding `#+OPTIONS: toc:1` or `#+toc: 1` in the front matter, but nothing seems to have any effect.

Is this not supported (and if so, could I suggest it as a request?) or am I doing something wrong?

Should I post this on the hugo repo instead?

Thanks! and thanks for the project :slightly_smiling_face: 

---

Hugo Version: 0.62.2
