### ISSUE TITLE
Will the org front matter support some structure like an associative array?

### ISSUE THREAD

**Issue by xinii** [niklasfasching/go-org#39]
First of all, thanks very much for your development to support our emacs org-mode users to use Hugo more conveniently.
I'm comfortable writing Hugo posts via org now, but I'm a little bit confused about the handling of the associative array.

For example, if there is a YAML front matter like this,

```yaml
title: an amazing title
tags:
- tag1
- tag2
menu:
  example:
    parent: Example Topic
    weight: 1
```

About the keys of `title` and `tags`, if write them by org matter, they will be,
```org
#+title: an amazing title
#+tags[]: tag1 tag2
```

However, how to handle the following YAML matter which contains some structure like an associative array through org matter?

```yaml
menu:
  example:
    parent: Example Topic
    weight: 1
```

I tried some combinations that didn't seem to work. Is there any good way to solve it?
